### ISSUE TITLE
Suggestions for lowering board cost on a mini board

### ISSUE THREAD

**Issue by nexusone1984** [PaintedBlck/S80#12]
I understand why you made so many boards, but for the learning experience, a lot of options is not required to get the basics of the Z80, program interface hardware. 

The goal, reduce the cost to make it more in reach of more people:

One boot EPROM is only needed, 8K is a very good size for booting or having a terminal with BASIC in that amount of memory.  If you want to boot with more then just basic, load CP/M use a single large Static RAM chip, with some logic like Grant uses.

If we reduce the number of chips in which the CPU has to drive we can do away with the data and address buffer chips. 

Make one clock source, just let the user choose which frequency they want to use for the system.

A serial port on board.

And a simple expansion port to connect I/O with the following connections:  IOREQ, M1, RD, WR, A0, A1, A2, A3, SELECT,  D0-D8, Ground, +5.   This would only require a 20 pin header. 

Since our I/O address space is 8 Bits you could have A4-A7 connected to a 74HCT21 dual 4 input OR gate to produce the SELECT signal, also use the other half for memory decoding. 

That gives out I/O expansion port 16 addresses at lower address space 0x00 - 0x0f.

With this could connect LCD's, a Z80 device, etc. 

Depending on space you could add a couple of extra chips to have a simple 8-bit input/out on the board for driving LED's or reading switches.

**Comment by PaintedBlck** [comment]
There seems t be a general trend to create a smaller board. We received an other remark that went in the same direction: small board that is able to run CP/M 2.2

The question is if we see such a small board as a version 2 or rather as a new project (e.g. S80C for Small Z80 computer running CP/M, or something like that). I'd rather opt for the second idea. That way, we don't block a potential further development of the S80 full-stack.

Your idea seems very feasible to me.

**Comment by kiwi47** [comment]
few spec's that I think a Small Z80 board should have 
64K SRAM being able to boot CPM 2.2 from SD Card 
2 serial ports , 8 bit GPIO Bus

**Comment by PaintedBlck** [comment]
Can CP/M run on 64kb without bank switching ?

**Comment by PaintedBlck** [comment]
Let's bring this discussion to issue https://github.com/PaintedBlck/S80/issues/13

I've invited a number of people to come over to GitHub for a further discussion on "the road ahead".
