### ISSUE TITLE
Copper Fill Should Not be flush With the Edge Cut

### ISSUE THREAD

**Issue by formix** [PaintedBlck/S80#17]
On the S80 V2 Processor Board, having the copper filling layers being flush with the edge cut increases the risk of having GND and VCC being shorted. 

Possible Issues: 

1) A conducting material (or dirty fingers) touches the board edges.
2) The board edge cutting process may bridge these two layers by leaving copper residues.

Edge cuts should be 1mm inlaid.

I did not check the other boards yet, this issues may exist on other boards as well.

**Comment by PaintedBlck** [comment]
I'll look into the issue. I'll also have a look at the first prototypes of the boards to see how the manufacturer finished the PCB.

**Comment by PaintedBlck** [comment]
Hi @formix ,

I have tried to abuse the edges of the test boards and of the production boards. I even have put solder around the edges. I didn't manage to create a short.

When looking at the edges with a microscope, I saw that the copper fillings stay about 0.5 mm from the edges.

Maybe this depends on the manufacturer?

Grtz.

**Comment by formix** [comment]
Possible, 1/2 mm seems reasonable to me.

Thanks for inquiring.
