### ISSUE TITLE
RetroZ SBC Bus Review Request

### ISSUE THREAD

**Issue by formix** [PaintedBlck/S80#18]
Hi,

I'm not sure if this is the right place to ask that since this is related to my own retro computer project that I'm converting to be compatible with the S80 specifications. If that is not the right place, I'll be pleased to move that discussion somewhere else.

To put you in context, I wanted to totally clear my mind off my own computer project before jumping 100% on the S80 video card. That is why I moved my stackable [RetroZ](https://github.com/formix/RetroZ) design to a single board computer leveraging the S80 board and BUS specifications. But the [template](https://www.dropbox.com/s/ncrq8tcz9pn0s4c/S80-Templates.png) I used don't mark the pin 1 precisely (or at least I don't understand the convention used). Is the pin 1 the square one (top left pin) or the pin that has no "hole" marked with a right angle (bottom left pin). I'm asking that because when I use the _20x2 pin header_ footprint, the pin 1 is the bottom left pin but when I take the _20x2 socket_, it is the top left pin.

On the same throw, I wanted to discuss the pin 1 of the user bus A (the left user bus that has Rx and Tx). Is this pin reserved for something else? I'm asking that because Rx ant Tx are on pin 2 and 3 and are the only reserved user port pins. If the pin 1 is not reserved, would it be possible for the future memory board (2Mb/4Mb) to set that pin HIGH to signal the memory board extension presence thus allowing my RetroZ-SBC board to deactivate the onboard RAM and ROM?

Finally, the RetroZ board is implementing interrupt chaining by using pint 1 to 5 of the user port B (the bottom right port). It is a bunch of blocked pins for that purpose but I tried to balance the number of interrupt enabled IO extension boards we could have for the project and the number of user port pin used.

1. Is it a good number, should I have more (or less)?
2. Should I move these signals to the user port A? That would totally use port A pins and leave all 8 port B pins free.

Thanks!

**Comment by formix** [comment]
Great! thanks for the answers. I'll update my schematics sometimes this weekto account for your feedbacks.

**Comment by formix** [comment]
Note that hardwiring the memory board user port A pin 1 to be a "Memory Board present" indicator may be a little bit circonstancial for my own project. In my documentation, I could explain how to add a jumper wire to do that as well.

**Comment by PaintedBlck** [comment]
Using a jumper wire seems a good alternative and more flexible.

Grtz!
